port: '/dev/ttyACM0'
baudrate: 115200
#output_data_file: '/home/droid/Documents/gps_data/gps_data.csv'
show_2d_map: false
show_google_map: false
show_gps_data: false
align:
  theta: -0.0360061882444
  scalar: -1.00857731524
  px: 90.4098510742
  py: -13.5929136276